### ISSUE TITLE
Are you going to fight the anticheats/ make updates?

### ISSUE THREAD

**Issue by YohSambre** [ItsJustDamian/GLua-Executor#1]
Hello, I wanted to thank you for your work however I have some questions:

- Do you intend to make future updates to improve it?
- Will you fight some anticheats ?

if you are interested in updating your loader i have listed a small list of anticheat that is circulating on garry's mod at the moment :
[g-security](https://steamcommunity.com/sharedfiles/filedetails/?id=1500242650)
[modernac](https://github.com/moderndx/Modern-Anti-Cheat)
[g-ac](https://github.com/GlorifiedPig/g-ac)

**Comment by ItsJustDamian** [comment]
> Hello, I wanted to thank you for your work however I have some questions:
> 
> * Do you intend to make future updates to improve it?
> * Will you fight some anticheats ?
> 
> if you are interested in updating your loader i have listed a small list of anticheat that is circulating on garry's mod at the moment :
> [g-security](https://steamcommunity.com/sharedfiles/filedetails/?id=1500242650)
> [modernac](https://github.com/moderndx/Modern-Anti-Cheat)
> [g-ac](https://github.com/GlorifiedPig/g-ac)

ye i might improve it and try to bypass some

**Comment by YohSambre** [comment]
I didn't expect to receive an answer so quickly ^^, I noticed some problems while trying it earlier today should I post them on github or send them to you in private on discord?

Yoh Sambre#9953

**Comment by pparadoxx** [comment]
> Hello, I wanted to thank you for your work however I have some questions:
> 
> * Do you intend to make future updates to improve it?
> * Will you fight some anticheats ?
> 
> if you are interested in updating your loader i have listed a small list of anticheat that is circulating on garry's mod at the moment :
> [g-security](https://steamcommunity.com/sharedfiles/filedetails/?id=1500242650)
> [modernac](https://github.com/moderndx/Modern-Anti-Cheat)
> [g-ac](https://github.com/GlorifiedPig/g-ac)

if you want to bypass anti cheats use a preautorun loader instead of just a regular loader
